name: keyburn
description: "Secret scanning for your repo (SARIF + CI blocking)."
inputs:
  path:
    description: "Path to scan."
    required: false
    default: "."
  fail_on:
    description: "Fail the job if any finding is >= this severity: low|medium|high."
    required: false
    default: "high"
  format:
    description: "Output format: text|json|sarif."
    required: false
    default: "sarif"
  sarif_file:
    description: "Where to write SARIF (when format=sarif)."
    required: false
    default: "keyburn.sarif"
  upload_sarif:
    description: "Upload SARIF to GitHub code scanning (requires security-events:write)."
    required: false
    default: "true"
  python_version:
    description: "Python version to use."
    required: false
    default: "3.12"
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install keyburn
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install "${GITHUB_ACTION_PATH}"

    - id: scan
      name: Scan
      shell: bash
      run: |
        set +e
        keyburn scan "${{ inputs.path }}" \
          --format "${{ inputs.format }}" \
          --out "${{ inputs.sarif_file }}" \
          --fail-on "${{ inputs.fail_on }}"
        ec=$?
        echo "exit_code=$ec" >> "$GITHUB_OUTPUT"
        exit 0

    - name: Upload SARIF
      if: ${{ inputs.upload_sarif == 'true' && inputs.format == 'sarif' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.sarif_file }}

    - name: Fail If Findings
      shell: bash
      run: |
        exit "${{ steps.scan.outputs.exit_code }}"

