name: keyburn
description: "Secret scanning for your repo (SARIF + CI blocking)."
inputs:
  path:
    description: "Path to scan."
    required: false
    default: "."
  fail_on:
    description: "Fail the job if any finding is >= this severity: low|medium|high."
    required: false
    default: "high"
  format:
    description: "Output format: text|json|sarif."
    required: false
    default: "sarif"
  sarif_file:
    description: "Where to write SARIF (when format=sarif)."
    required: false
    default: "keyburn.sarif"
  upload_sarif:
    description: "Upload SARIF to GitHub code scanning (requires security-events:write)."
    required: false
    default: "true"
  comment_pr:
    description: "Post or update a PR comment with a scan summary (pull_request only)."
    required: false
    default: "false"
  comment_findings:
    description: "How many findings to include in the PR comment table."
    required: false
    default: "10"
  comment_file:
    description: "JSON report path used internally for PR comments."
    required: false
    default: "keyburn.findings.json"
  python_version:
    description: "Python version to use."
    required: false
    default: "3.12"
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install keyburn
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install "${GITHUB_ACTION_PATH}"

    - id: scan
      name: Scan
      shell: bash
      run: |
        set +e
        keyburn scan "${{ inputs.path }}" \
          --format "${{ inputs.format }}" \
          --out "${{ inputs.sarif_file }}" \
          --fail-on "${{ inputs.fail_on }}"
        ec=$?
        echo "exit_code=$ec" >> "$GITHUB_OUTPUT"

        if [ "${{ inputs.comment_pr }}" = "true" ]; then
          keyburn scan "${{ inputs.path }}" \
            --format json \
            --out "${{ inputs.comment_file }}" \
            --fail-on low >/dev/null 2>&1 || true
        fi

        exit 0

    - name: Upload SARIF
      if: ${{ inputs.upload_sarif == 'true' && inputs.format == 'sarif' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.sarif_file }}

    - name: Comment On Pull Request
      if: ${{ inputs.comment_pr == 'true' && github.event_name == 'pull_request' }}
      uses: actions/github-script@v7
      env:
        KEYBURN_COMMENT_FILE: ${{ inputs.comment_file }}
        KEYBURN_FAIL_ON: ${{ inputs.fail_on }}
        KEYBURN_MAX_FINDINGS: ${{ inputs.comment_findings }}
      with:
        github-token: ${{ github.token }}
        script: |
          const fs = require("fs");

          const marker = "<!-- keyburn-pr-comment -->";
          const issueNumber = context.payload.pull_request?.number;
          if (!issueNumber) {
            core.info("Not a pull request context, skipping PR comment.");
            return;
          }

          const reportPath = process.env.KEYBURN_COMMENT_FILE;
          if (!fs.existsSync(reportPath)) {
            core.warning(`Missing comment report file: ${reportPath}`);
            return;
          }

          let payload;
          try {
            payload = JSON.parse(fs.readFileSync(reportPath, "utf8"));
          } catch (error) {
            core.warning(`Unable to parse ${reportPath}: ${error.message}`);
            return;
          }

          const summary = payload.summary || {};
          const findings = Array.isArray(payload.findings) ? payload.findings : [];
          const maxFindings = Math.max(1, Number(process.env.KEYBURN_MAX_FINDINGS || "10"));
          const shown = findings.slice(0, maxFindings);
          const failOn = process.env.KEYBURN_FAIL_ON || "high";

          const lines = [];
          lines.push(marker);
          lines.push("## keyburn scan");
          lines.push("");
          lines.push(
            `Summary: **${summary.total || 0}** findings ` +
            `(high=${summary.high || 0}, medium=${summary.medium || 0}, low=${summary.low || 0})`
          );
          lines.push(`Fail threshold: \`${failOn}\``);

          if (shown.length > 0) {
            lines.push("");
            lines.push("| Severity | Rule | Location |");
            lines.push("|---|---|---|");
            for (const finding of shown) {
              const sev = String(finding.severity || "").toUpperCase();
              const rule = String(finding.pattern_id || "");
              const location = `${finding.path || ""}:${finding.line || ""}`;
              lines.push(`| ${sev} | \`${rule}\` | \`${location}\` |`);
            }
          }

          if (findings.length > shown.length) {
            lines.push("");
            lines.push(`...and ${findings.length - shown.length} more finding(s).`);
          }

          lines.push("");
          lines.push("_Generated by keyburn action._");
          const body = lines.join("\n");

          const { owner, repo } = context.repo;

          try {
            const comments = await github.paginate(github.rest.issues.listComments, {
              owner,
              repo,
              issue_number: issueNumber,
              per_page: 100,
            });

            const existing = comments.find((comment) => comment.body && comment.body.includes(marker));

            if (existing) {
              await github.rest.issues.updateComment({
                owner,
                repo,
                comment_id: existing.id,
                body,
              });
              core.info(`Updated keyburn PR comment (${existing.id}).`);
            } else {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: issueNumber,
                body,
              });
              core.info("Created keyburn PR comment.");
            }
          } catch (error) {
            core.warning(`Failed to create/update PR comment: ${error.message}`);
          }

    - name: Fail If Findings
      shell: bash
      run: |
        exit "${{ steps.scan.outputs.exit_code }}"
